const esc = s => String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const t = (en,ru) => `<span data-en="${esc(en)}" data-ru="${esc(ru)}">${esc(en)}</span>`;
const arrow = '<span class="arrow" aria-hidden="true">↗</span>';
const label = (en,ru) => `<div class="eyebrow">${t(en,ru)}</div>`;
const official = 'https://tcmall.uz/en/catalog/shops';
const out = (url,text,cls='') => `<a class="${cls}" href="${url}" target="_blank" rel="noopener noreferrer">${text}${arrow}</a>`;
const stores = [
 ['ZARA','fashion','', 'Everyday, with character','Стиль на каждый день','Jeans, shirts, dresses and jackets for a fresh everyday look.','Джинсы, рубашки, платья и куртки для нового повседневного образа.'],
 ['Massimo Dutti','fashion','dark','A more refined wardrobe','Более сдержанный гардероб','Smart shirts, trousers and knitwear when you want a classic style.','Рубашки, брюки и трикотаж для тех, кто предпочитает классический стиль.'],
 ['PULL&BEAR','fashion','mono','Relaxed & expressive','Свободно и выразительно','Casual clothes, T-shirts and denim for relaxed days with friends.','Повседневная одежда, футболки и джинсы для прогулок с друзьями.'],
 ['adidas','sport','sport','Made to move','Для тех, кто в движении','Trainers, sportswear and accessories for an active lifestyle.','Кроссовки, спортивная одежда и аксессуары для активного образа жизни.'],
 ['Bershka','fashion','mono dark','Find your own style','Найди свой стиль','Youth fashion, denim and casual pieces to mix into your wardrobe.','Молодёжная мода, джинсовая одежда и вещи для повседневных сочетаний.'],
 ['NIKE','sport','sport','Sport meets the street','Спорт в городском стиле','Athletic shoes and sports clothing for training and everyday wear.','Спортивная обувь и одежда для тренировок и повседневной жизни.'],
 ['ZARA HOME','home','mono','Small details, big difference','Детали меняют всё','Bedding, towels and home accessories to make a room feel your own.','Постельное бельё, полотенца и аксессуары, которые делают дом уютнее.'],
 ['Stradivarius','fashion','','Your next favourite outfit','Твой новый любимый образ','Women’s clothing and accessories, from everyday basics to statement pieces.','Женская одежда и аксессуары: от базовых вещей до ярких деталей образа.']
];
const categoryName = c => c==='fashion'?t('Fashion','Одежда'):c==='sport'?t('Sport & sneakers','Спорт и кроссовки'):t('Home & lifestyle','Дом и уют');
const shopCards = stores.map((s,i)=>`<article class="shop-card" data-category="${s[1]}"><div class="shop-logo ${s[2]}"><small>0${i+1} / TCM</small>${s[0]}</div><div class="shop-card-body"><div class="card-meta">${categoryName(s[1])}<span>↗</span></div><h3>${t(s[3],s[4])}</h3><p>${t(s[5],s[6])}</p>${out(official,t('Official directory','Официальный каталог'))}</div></article>`).join('');
const categories = [
 ['◈','Fashion & footwear','Одежда и обувь','Build an outfit: jeans, a shirt, a jacket and a pair of trainers.','Собери образ: джинсы, рубашка, куртка и пара кроссовок.'],
 ['✧','Beauty & fragrance','Красота и парфюмерия','Explore cosmetics and perfumes. Compare scents before choosing.','Познакомься с косметикой и парфюмерией. Сравни ароматы перед выбором.'],
 ['⌘','Electronics & mobile','Электроника и связь','Look for phones, headphones and useful everyday accessories.','Присмотри телефон, наушники и полезные повседневные аксессуары.'],
 ['⌂','Home & living','Товары для дома','Find textiles and decorative details for a comfortable home.','Найди текстиль и декоративные детали для уютного дома.'],
 ['✳','Kids & gifts','Детям и в подарок','Choose toys, children’s clothing or a small present for someone special.','Выбери игрушки, детскую одежду или небольшой подарок близкому человеку.'],
 ['◇','Accessories & jewellery','Аксессуары и украшения','Add the finishing touch with a bag, watch or piece of jewellery.','Дополни образ сумкой, часами или украшением.']
].map(c=>`<article class="category"><div class="cat-icon" aria-hidden="true">${c[0]}</div><div><h3>${t(c[1],c[2])}</h3><p>${t(c[3],c[4])}</p></div></article>`).join('');
const food = [
 ['☕','PAUL','Café & bakery','Кафе и пекарня','A coffee and bakery stop between shops.','Кофе и выпечка в перерыве между покупками.'],
 ['✿','SAFIA','Café & desserts','Кафе и десерты','A sweet break with a cake or a pastry.','Сладкий перерыв с пирожным или выпечкой.'],
 ['〰','TANUKI','Restaurant','Ресторан','Japanese-inspired food for a longer lunch.','Блюда японской кухни для неспешного обеда.'],
 ['✦','BIG CHEFS','Restaurant','Ресторан','A sit-down meal and time to catch up.','Обед в ресторане и время пообщаться.'],
 ['≋','KFC','Food court','Фудкорт','A familiar chicken option for a quick bite.','Знакомые блюда из курицы для быстрого перекуса.'],
 ['△','PIZZA HUT','Food court','Фудкорт','Pizza is an easy choice to share with friends.','Пицца — удобный вариант для компании друзей.']
].map(f=>`<article class="food-card"><div class="food-icon" aria-hidden="true">${f[0]}</div><h3>${f[1]}</h3><small>${t(f[2],f[3])}</small><p>${t(f[4],f[5])}</p></article>`).join('');
const comparisons = [
 ['What to buy','Что купить','International fashion, sportswear, electronics and home accessories in separate stores.','Международные бренды одежды, спортивные товары, электроника и товары для дома в отдельных магазинах.','Fresh produce, spices, dried fruit and traditional goods. The range depends on the bazaar.','Свежие продукты, специи, сухофрукты и традиционные товары. Ассортимент зависит от конкретного базара.'],
 ['Comfort','Комфорт','Indoor galleries make it easier to keep shopping in hot, cold or rainy weather.','Крытые галереи позволяют комфортнее делать покупки в жару, холод или дождь.','Covered stalls offer shelter, but outdoor areas are more affected by the weather.','Крытые ряды защищают от непогоды, но открытые участки сильнее зависят от погоды.'],
 ['Prices','Цены','Price tags make comparing items straightforward. Branded products can cost more.','Ценники помогают сравнивать товары. Брендовые вещи могут стоить дороже.','Bargaining is often part of the experience. Some goods may be cheaper, but compare quality too.','Торг часто становится частью покупки. Некоторые товары могут быть дешевле, но стоит сравнивать и качество.'],
 ['Food & breaks','Еда и перерывы','Cafés, a food court and restaurants offer different ways to take a break.','Кафе, фудкорт и рестораны позволяют выбрать удобный вариант отдыха.','Local dishes and street food can turn a shopping trip into a taste of the city.','Местные блюда и уличная еда помогают познакомиться со вкусами города.'],
 ['Things to do','Чем заняться','Shopping can be combined with Cinematica or Sky Park in the same complex.','Покупки можно совместить с Cinematica или Sky Park в одном комплексе.','Talking to sellers and discovering local products are a big part of the experience.','Общение с продавцами и знакомство с местными товарами — важная часть впечатлений.'],
 ['Atmosphere','Атмосфера','Modern architecture, shop windows and a planned shopping route. Busy weekends can still be crowded.','Современная архитектура, витрины и продуманный маршрут покупок. По выходным здесь тоже бывает многолюдно.','A lively, traditional setting with local character, conversations and everyday city life.','Живая традиционная среда с местным колоритом, общением и повседневной жизнью города.']
].map(r=>`<div class="compare-row" role="row"><div role="rowheader">${t(r[0],r[1])}</div><div role="cell">${t(r[2],r[3])}</div><div role="cell">${t(r[4],r[5])}</div></div>`).join('');
const photos = [
 ['atrium.jpg','A new perspective','Новый ракурс','The multi-level atrium at Tashkent City Mall','Многоуровневый атриум Tashkent City Mall'],
 ['exterior.jpg','The city outside','Город снаружи','Tashkent City Mall and the Summit tower','Tashkent City Mall и башня Summit'],
 ['shopping.jpg','Inside the mall','Внутри торгового центра','Shops and galleries inside Tashkent City Mall','Магазины и галереи внутри Tashkent City Mall'],
 ['aerial.jpg','In the heart of Tashkent','В сердце Ташкента','Aerial photograph of Tashkent City Mall and the surrounding buildings','Фотография Tashkent City Mall и окружающих зданий с высоты']
];
document.querySelector('#app').innerHTML = `
<header class="topbar"><div class="wrap nav-wrap"><a class="brand" href="#home" aria-label="Tashkent City Mall"><span class="brand-mark">T</span><span class="brand-name">TASHKENT CITY<small>MALL · ${t('THE CITY GUIDE','ГИД ПО ГОРОДУ')}</small></span></a><nav id="navigation" class="navlinks" aria-label="Main navigation"><a href="#about">${t('Discover','О месте')}</a><a href="#shopping">${t('Shopping','Магазины')}</a><a href="#food">${t('Food & fun','Еда и отдых')}</a><a href="#comparison">${t('Mall vs Bazaar','Молл и базар')}</a><a href="#gallery">${t('Gallery','Галерея')}</a></nav><div class="nav-actions"><div class="lang" aria-label="Language / Язык"><button class="active" data-lang="en" aria-pressed="true" aria-label="English">EN</button><button data-lang="ru" aria-pressed="false" aria-label="Русский">RU</button></div><button class="menu-toggle" aria-controls="navigation" aria-expanded="false" data-label-en="Open menu" data-label-ru="Открыть меню" aria-label="Open menu">☰</button></div></div></header>
<main>
<section class="hero" id="home"><div class="hero-photo" role="img" data-label-en="Aerial view of Tashkent City Mall" data-label-ru="Tashkent City Mall с высоты" aria-label="Aerial view of Tashkent City Mall"></div><div class="wrap hero-content"><div class="hero-meta"><span class="pill">✳ ${t('A NEW PERSPECTIVE ON SHOPPING','НОВЫЙ ВЗГЛЯД НА ПОКУПКИ')}</span><span class="location">↗ ${t('Tashkent, Uzbekistan','Ташкент, Узбекистан')}</span></div><h1>TASHKENT<br>CITY <span class="outlined">MALL</span><span class="red">.</span></h1><h2 class="hero-subtitle">${t('More than a shopping destination.','Больше, чем место для покупок.')}</h2><div class="hero-bottom"><div><p>${t('A place to find your style, try something new and spend a day together. Discover a modern side of Tashkent.','Место, где можно найти свой стиль, попробовать новое и провести день вместе. Открой современную сторону Ташкента.')}</p><div class="hero-cta"><a class="button primary" href="#about">${t('Explore the mall','Открыть торговый центр')}${arrow}</a><a class="text-link" href="#architecture">${t('View in 3D','Посмотреть в 3D')}<span>◈</span></a></div></div><div class="hero-index">${t('ONE DESTINATION','ОДНО МЕСТО')}<strong>${t('Endless possibilities.','Множество возможностей.')}</strong>${t('SHOP · TASTE · EXPERIENCE','ПОКУПКИ · ВКУСЫ · ВПЕЧАТЛЕНИЯ')}</div></div><div class="hero-scroll"><span>↓ ${t('Scroll to discover','Листай и открывай')}</span><span>${t('An English project · A local perspective','Проект по английскому · Взгляд на свой город')}</span></div></div></section>
<div class="marquee" aria-hidden="true">${t('FASHION & LIFESTYLE','МОДА И СТИЛЬ')}<b>✳</b>${t('FOOD & CONVERSATION','ЕДА И ОБЩЕНИЕ')}<b>✳</b>${t('CINEMA & ENTERTAINMENT','КИНО И РАЗВЛЕЧЕНИЯ')}<b>✳</b>${t('IN THE HEART OF TASHKENT','В СЕРДЦЕ ТАШКЕНТА')}</div>
<section class="section wrap" id="about"><div class="about-grid"><div class="about-image reveal"><img src="assets/atrium.jpg" alt="Bright atrium at Tashkent City Mall" data-alt-en="Bright atrium at Tashkent City Mall" data-alt-ru="Светлый атриум Tashkent City Mall" loading="lazy"><div class="image-stamp"><div>${t('A DIFFERENT KIND OF','НОВЫЙ ВЗГЛЯД НА')}<br><strong>${t('Everyday experience.','Повседневный отдых.')}</strong></div><span class="arrow">↗</span></div></div><div class="about-copy reveal">${label('01 / Meet the mall','01 / Знакомство')}<h2>${t('A whole day.','Целый день.')}<br>${t('One address.','Один адрес.')}</h2><p>${t('Tashkent City Mall is a modern shopping and entertainment centre in the Tashkent City district. It brings shops, places to eat and leisure activities together in one complex.','Tashkent City Mall — современный торгово-развлекательный центр в районе Tashkent City. Здесь в одном комплексе собраны магазины, заведения и возможности для отдыха.')}</p><p>${t('You can look for a new outfit, stop for coffee and watch a film without travelling to different parts of the city. Its open atrium, glass roof and surrounding skyline make the building part of the experience.','Можно подобрать новый образ, выпить кофе и посмотреть фильм, не переезжая из одной части города в другую. Просторный атриум, стеклянная крыша и окружающие высотки тоже становятся частью впечатлений.')}</p><div class="facts-line"><div><strong>2024</strong><small>${t('The year the mall opened','Год открытия торгового центра')}</small></div><div><strong>${t('City centre','Центр города')}</strong><small>${t('7 Botir Zokirov Street','Улица Ботира Закирова, 7')}</small></div></div><a href="#comparison" class="text-link">${t('How does it compare to a bazaar?','Чем он отличается от базара?')}${arrow}</a></div></div></section>
<section class="section scene-section wrap" id="architecture"><div class="section-head reveal"><div>${label('02 / Architecture in motion','02 / Архитектура в движении')}<h2>${t('A landmark.','Архитектура.')}<br><span class="red">${t('From every angle.','С любого ракурса.')}</span></h2></div><p>${t('Explore our interactive architectural interpretation of the mall, its glass towers and the surrounding cityscape.','Изучи нашу интерактивную архитектурную интерпретацию молла, стеклянных башен и окружающего городского пространства.')}</p></div><div class="scene-shell"><div id="scene" tabindex="0" role="img" aria-label="Interactive 3D architectural model. Use arrow keys to rotate and plus or minus to zoom." data-label-en="Interactive 3D architectural model. Use arrow keys to rotate and plus or minus to zoom." data-label-ru="Интерактивная архитектурная 3D-модель. Стрелки — вращение, плюс и минус — масштаб."></div><div class="scene-fallback" id="scene-fallback" hidden><p>${t('The 3D view is unavailable in this browser. Explore the real aerial photograph instead.','3D-вид недоступен в этом браузере. Перед тобой реальная фотография комплекса с высоты.')}</p></div><div class="scene-label"><strong>TASHKENT CITY MALL</strong><small>${t('Architectural study / Interactive 3D','Архитектурный этюд / Интерактивная 3D-сцена')}</small></div><span class="pill scene-badge">● ${t('EXPLORE IN 3D','ИССЛЕДУЙ В 3D')}</span><div class="scene-tip">↔ ${t('Drag to rotate · Use + / − to zoom','Потяни для вращения · Масштаб: + / −')}</div><div class="scene-controls"><button class="rotate" id="auto-rotate" aria-pressed="false">${t('Auto-rotate','Автовращение')}</button><button id="zoom-in" aria-label="Zoom in" data-label-en="Zoom in" data-label-ru="Приблизить">+</button><button id="zoom-out" aria-label="Zoom out" data-label-en="Zoom out" data-label-ru="Отдалить">−</button><button id="reset-view" aria-label="Reset view" data-label-en="Reset view" data-label-ru="Сбросить вид">↺</button></div></div><div class="scene-note"><span>${t('Original illustrative model based on exterior photographs. Building shapes, distances and neighbouring structures are simplified; this is not a survey or a navigation map.','Авторская иллюстративная модель по фотографиям фасада. Формы зданий, расстояния и соседние постройки упрощены; это не инженерная модель и не навигационная карта.')}</span><a class="text-link" href="#gallery">${t('See the real place','Посмотреть реальные фото')} ↗</a></div></section>
<section class="section wrap rule" id="shopping"><div class="section-head reveal"><div>${label('03 / Find your favourites','03 / Найди своё')}<h2>${t('Your style.','Твой стиль.')}<br>${t('Your shopping day.','Твой день покупок.')}</h2></div><p>${t('Real brands. Different styles. Here are selected stores at Tashkent City Mall and the kinds of things you can look for.','Реальные бренды и разные стили. Вот несколько магазинов Tashkent City Mall и примеры того, что в них можно найти.')}</p></div><div class="tabs" role="group" aria-label="Store categories"><button class="tab active" data-filter="all" aria-pressed="true">${t('All stores','Все магазины')}</button><button class="tab" data-filter="fashion" aria-pressed="false">${t('Fashion','Одежда')}</button><button class="tab" data-filter="sport" aria-pressed="false">${t('Sport & sneakers','Спорт и кроссовки')}</button><button class="tab" data-filter="home" aria-pressed="false">${t('Home & lifestyle','Дом и уют')}</button></div><div class="shop-grid" aria-live="polite">${shopCards}</div><p class="source-note">${t('A selected guide, not a full store list. Product ranges change. Sources:','Подборка, а не полный список магазинов. Ассортимент меняется. Источники:')} <a href="https://www.sarda-group.com/news/vzxsz85izkc3j3jnrcvyb3w7c4pwnq-8dgcp" target="_blank" rel="noopener noreferrer">SARDA Group</a> · <a href="https://telegram.me/s/Tashkent_City_Mall?before=2586" target="_blank" rel="noopener noreferrer">${t('Mall brand announcements','Бренды в публикациях молла')}</a> · <a href="${official}" target="_blank" rel="noopener noreferrer">${t('Current directory','Актуальный каталог')}</a></p><div class="categories">${categories}</div></section>
<section class="section food-section" id="food"><div class="wrap"><div class="section-head reveal"><div>${label('04 / Take a delicious break','04 / Вкусный перерыв')}<h2>${t('Good taste.','Хороший вкус.')}<br>${t('Great company.','Отличная компания.')}</h2></div><p>${t('A shopping day needs a food break. Choose a quick snack, a slow lunch or something sweet — all inside the mall.','В день покупок нужен перерыв на еду. Выбирай быстрый перекус, неспешный обед или что-нибудь сладкое — всё внутри молла.')}</p></div><div class="food-layout"><div class="food-photo"><img src="assets/interior.jpg" alt="Sunlit shopping galleries at Tashkent City Mall" data-alt-en="Sunlit shopping galleries at Tashkent City Mall" data-alt-ru="Залитые светом торговые галереи Tashkent City Mall" loading="lazy"><div class="photo-copy"><span class="pill">${t('PAUSE. TASTE. ENJOY.','ОСТАНОВИСЬ. ПОПРОБУЙ. НАСЛАДИСЬ.')}</span><h3 style="margin-top:20px">${t('Make time for','Найди время для')}<br>${t('the little moments.','маленьких радостей.')}</h3><p>${t('For me, a café break is not just about food. It is a chance to sit down, talk and enjoy the day.','Для меня перерыв в кафе — это не только еда. Это возможность присесть, поговорить и насладиться днём.')}</p></div></div><div class="food-list">${food}</div></div><p class="source-note">${t('These venues appear in the mall’s food directory. Menus and availability can change.','Эти заведения указаны в каталоге питания молла. Меню и доступность могут меняться.')} <a href="https://tcmall.uz/uz/catalog/restaurants?sort=1&view=1" target="_blank" rel="noopener noreferrer">${t('Explore the official food directory ↗','Официальный каталог заведений ↗')}</a></p></div></section>
<section class="section wrap" id="entertainment"><div class="section-head reveal"><div>${label('05 / Stay for the experience','05 / Останься ради впечатлений')}<h2>${t('The day doesn’t','День не заканчивается')}<br>${t('end at checkout.','после покупки.')}</h2></div><p>${t('You do not have to buy something to enjoy a visit. Make room in your plans for a film, an activity or a walk.','Чтобы получить удовольствие от посещения, необязательно что-то покупать. Оставь время на фильм, развлечения или прогулку.')}</p></div><div class="ent-grid"><article class="ent-card"><div class="ent-symbol">IMAX<span class="red">®</span></div><div><h3>Cinematica</h3><p>${t('Make a film the final stop of your day. Cinematica at the mall includes an IMAX experience. Check the current schedule, age rating and language before booking.','Заверши день фильмом. В Cinematica в молле есть зал IMAX. Перед покупкой проверь расписание, возрастной рейтинг и язык сеанса.')}</p></div>${out('https://cinematica.uz/',t('Check film times','Посмотреть сеансы'))}</article><article class="ent-card"><div class="ent-symbol">SKY<br>PARK ↗</div><div><h3>${t('Play. Discover. Repeat.','Играй. Узнавай. Повторяй.')}</h3><p>${t('Sky Park is the mall’s family entertainment space. It adds active fun to a day that would otherwise be only about shopping.','Sky Park — семейное развлекательное пространство молла. Оно добавляет активный отдых в день, который иначе был бы посвящён только покупкам.')}</p></div>${out('https://tcmall.uz/ru/entertainments/skypark',t('Discover Sky Park','Познакомиться со Sky Park'))}</article><article class="ent-card"><div class="ent-symbol">↗ ↗</div><div><h3>${t('Step into the city.','Выйди навстречу городу.')}</h3><p>${t('Tashkent City Park is next to the complex. After your visit, continue with a walk and a different view of the skyline. This is an outdoor stop, outside the mall.','Рядом с комплексом находится Tashkent City Park. После посещения прогуляйся и взгляни на городской пейзаж с другой стороны. Это прогулка на улице, за пределами молла.')}</p></div><a href="#gallery">${t('See the surroundings','Посмотреть окрестности')}${arrow}</a></article></div></section>
<section class="section wrap rule" id="facts">${label('06 / Worth a closer look','06 / Интересные детали')}<div class="section-head"><h2>${t('Beyond the shop windows.','Больше, чем витрины.')}</h2></div><div class="fact-grid"><article class="fact"><div class="fact-number">01 /</div><h3>${t('A new chapter in 2024','Новая глава в 2024 году')}</h3><p>${t('The mall opened in 2024. Its opening brought a new group of international fashion stores to Tashkent, including Zara and other Inditex brands.','Молл открылся в 2024 году. Его открытие привело в Ташкент новые магазины международных брендов, включая Zara и другие бренды Inditex.')}</p></article><article class="fact"><div class="fact-number">02 /</div><h3>${t('Look up, not just around','Смотри не только по сторонам')}</h3><p>${t('The central atrium and curved glass roof are part of the mall’s visual identity. From the galleries, you can see several levels at once.','Центральный атриум и изогнутая стеклянная крыша — часть узнаваемого облика молла. Из галерей можно увидеть сразу несколько уровней.')}</p></article><article class="fact"><div class="fact-number">03 /</div><h3>${t('Part of a bigger picture','Часть большого пространства')}</h3><p>${t('The mall stands beside glass towers and Tashkent City Park. Shopping, business and outdoor leisure meet in the same urban setting.','Молл соседствует со стеклянными башнями и Tashkent City Park. Покупки, деловая жизнь и отдых на улице объединены в одной городской среде.')}</p></article></div></section>
<section class="section compare" id="comparison"><div class="wrap"><div class="compare-intro reveal">${label('07 / Two ways to discover Tashkent','07 / Два способа узнать Ташкент')}<h2>${t('Mall','Молл')}<em>vs</em>${t('Bazaar','Базар')}<span class="red">.</span></h2><p>${t('Two different experiences. Both have something to offer. The best choice depends on what you want from your day.','Два разных впечатления. У каждого варианта есть свои плюсы. Лучший выбор зависит от того, как ты хочешь провести день.')}</p></div><div class="compare-table" role="table" aria-label="Mall versus traditional bazaar" data-label-en="Mall versus traditional bazaar" data-label-ru="Сравнение молла и традиционного базара"><div class="compare-row table-head" role="row"><div role="columnheader">${t('THE EXPERIENCE','ВПЕЧАТЛЕНИЯ')}</div><div role="columnheader">Tashkent City Mall<small>${t('Modern. Convenient. Connected.','Современно. Удобно. Всё рядом.')}</small></div><div role="columnheader">${t('A traditional bazaar','Традиционный базар')}<small>${t('Local. Lively. Full of character.','Местный колорит. Жизнь. Традиции.')}</small></div></div>${comparisons}</div><div class="verdict"><article class="verdict-card">${label('My choice for a shopping day','Мой выбор для дня покупок')}<h3>${t('The mall makes planning easier.','В молле проще спланировать день.')}</h3><p>${t('If I want clothes, lunch and a film with friends, Tashkent City Mall is more convenient for me. I can move between activities indoors, compare shop prices and meet everyone in one place. That saves travel time and makes the day easier to organise.','Если я хочу купить одежду, пообедать и посмотреть кино с друзьями, Tashkent City Mall для меня удобнее. Можно переходить между занятиями внутри здания, сравнивать цены в магазинах и встретиться всем в одном месте. Это экономит время на дорогу и упрощает организацию дня.')}</p></article><article class="verdict-card">${label('A different kind of value','Ценность другого опыта')}<h3>${t('The bazaar has its own magic.','У базара есть своё очарование.')}</h3><p>${t('For fresh ingredients, spices or a more traditional atmosphere, I would choose a bazaar. Bargaining and speaking with sellers can be memorable experiences. A mall does not replace this part of local culture — it offers another way to shop.','За свежими продуктами, специями или более традиционной атмосферой я бы пошёл на базар. Торг и общение с продавцами могут запомниться надолго. Молл не заменяет эту часть местной культуры — он предлагает другой способ делать покупки.')}</p></article></div><p class="source-note">${t('The bazaar column describes a typical traditional market, not every bazaar. Prices, facilities and products vary by place and seller.','Колонка о базаре описывает типичный традиционный рынок, а не каждый базар. Цены, удобства и товары зависят от места и продавца.')}</p></div></section>
<section class="section wrap" id="opinion">${label('08 / My opinion','08 / Моё мнение')}<div class="opinion-layout"><aside class="opinion-aside"><div class="avatar">DR</div><div><strong>${t('David Rusinov','Давид Русинов')}</strong><small>${t('Class 11A · English project','11А класс · Проект по английскому')}</small></div></aside><div class="opinion-copy reveal"><div class="quote-mark" aria-hidden="true">“</div><blockquote>${t('I would choose Tashkent City Mall for a modern shopping day because it brings the things I enjoy into one place: fashion, food and time with friends.','Для современного дня покупок я бы выбрал Tashkent City Mall, потому что здесь в одном месте собрано то, что мне нравится: мода, еда и время с друзьями.')}</blockquote><p>${t('What I like most is the freedom to make a simple plan: look around the shops, have lunch and finish with a film. I would set a budget first, because a beautiful shop window can make almost anything look tempting! I also think bazaars are important: they keep local traditions alive and offer a different kind of shopping experience. For me, the mall is the more convenient choice for this particular day, but both places belong in Tashkent’s story.','Больше всего мне нравится возможность составить простой план: пройтись по магазинам, пообедать и закончить день фильмом. Сначала я бы определил бюджет, потому что красивая витрина делает почти любую вещь заманчивой! Я также считаю базары важными: они сохраняют местные традиции и предлагают другой опыт покупок. Для такого дня молл удобнее, но оба места являются частью истории Ташкента.')}</p><div class="opinion-tags"><span class="pill">${t('Convenience','Удобство')}</span><span class="pill">${t('Choice','Выбор')}</span><span class="pill">${t('Time with friends','Время с друзьями')}</span><span class="pill">${t('Respect for tradition','Уважение к традициям')}</span></div></div></div><div class="itinerary"><div class="itinerary-top"><h3>${t('My perfect shopping day.','Мой идеальный день покупок.')}</h3><p>${t('An example plan, not a venue timetable. Set your budget and check film times first.','Пример плана, а не расписание заведений. Сначала определи бюджет и проверь сеансы.')}</p></div><div class="day-grid">${[
 ['01','Look around','Осмотреться','Start with fashion and sportswear. Try things on and compare.','Начать с одежды и спортивных товаров. Примерить и сравнить.'],
 ['02','Take a break','Сделать перерыв','Choose lunch together, then stop for a coffee or dessert.','Вместе выбрать обед, затем выпить кофе или съесть десерт.'],
 ['03','Make a memory','Получить впечатления','Watch a film at Cinematica or choose a family activity.','Посмотреть фильм в Cinematica или выбрать семейный отдых.'],
 ['04','Enjoy the city','Насладиться городом','End with a walk by the park and a view of the towers.','Завершить день прогулкой у парка с видом на высотки.']
].map(d=>`<div class="day-step"><small>${d[0]} —</small><strong>${t(d[1],d[2])}</strong><p>${t(d[3],d[4])}</p></div>`).join('')}</div></div></section>
<section class="section wrap rule" id="gallery"><div class="section-head reveal"><div>${label('09 / Through the lens','09 / Через объектив')}<h2>${t('See the place.','Увидеть место.')}<br>${t('Feel the atmosphere.','Почувствовать атмосферу.')}</h2></div><p>${t('Real photographs of Tashkent City Mall. Open any image to take a closer look.','Реальные фотографии Tashkent City Mall. Открой любое изображение, чтобы рассмотреть его подробнее.')}</p></div><div class="gallery-grid">${photos.map((p,i)=>`<button class="gallery-item" data-photo="${i}" aria-label="${esc('Open photo: '+p[1])}" data-label-en="${esc('Open photo: '+p[1])}" data-label-ru="${esc('Открыть фото: '+p[2])}"><img src="assets/${p[0]}" alt="${esc(p[3])}" data-alt-en="${esc(p[3])}" data-alt-ru="${esc(p[4])}" loading="lazy"><span class="gallery-caption">${t(p[1],p[2])}<b>↗</b></span></button>`).join('')}</div><p class="source-note">${t('Photography: Afisha.uz, Tashkent City Mall, Kursiv Media and SARDA Group. Original publications are linked below.','Фотографии: Afisha.uz, Tashkent City Mall, Kursiv Media и SARDA Group. Ссылки на оригинальные публикации — ниже.')}</p></section>
<section class="wrap" id="visit"><div class="visit-box"><div class="visit-copy">${label('10 / Your next city day','10 / Твой следующий день в городе')}<h2>${t('Find your way here.','Найди дорогу сюда.')}</h2><p>${t('Tashkent City Mall · 7 Botir Zokirov Street, Tashkent, Uzbekistan. Check the official website for opening hours, the mall map and the latest updates before visiting.','Tashkent City Mall · Узбекистан, Ташкент, улица Ботира Закирова, 7. Перед посещением проверь часы работы, схему молла и последние новости на официальном сайте.')}</p><div class="visit-links">${out('https://www.google.com/maps/search/?api=1&query=Tashkent+City+Mall+Tashkent',t('Open map','Открыть карту'),'button primary')}${out('https://tcmall.uz/en',t('Official website','Официальный сайт'),'button')}</div></div><div class="visit-image"><img src="assets/exterior.jpg" alt="Exterior of Tashkent City Mall" data-alt-en="Exterior of Tashkent City Mall" data-alt-ru="Фасад Tashkent City Mall" loading="lazy"></div></div></section>
<section class="wrap sources" id="sources"><details><summary>${t('Sources, photo credits & project notes','Источники, авторство фото и примечания')}</summary><div class="source-content"><p>${t('Researched on 12 September 2026. This is an independent school project, not the official mall website. Store ranges, tenants and schedules may change. The comparison and My Opinion are the project’s own writing; the 3D scene is an illustrative reconstruction.','Проверено 12 сентября 2026 года. Это самостоятельный школьный проект, а не официальный сайт молла. Ассортимент, арендаторы и расписание могут меняться. Сравнение и «Моё мнение» — авторские тексты проекта; 3D-сцена — иллюстративная реконструкция.')}</p><ol>
<li><a href="https://tcmall.uz/en" target="_blank" rel="noopener noreferrer">Tashkent City Mall</a> — ${t('official information and address','официальная информация и адрес')}.</li>
<li><a href="https://tcmall.uz/en/catalog/shops" target="_blank" rel="noopener noreferrer">${t('Official shopping directory','Официальный каталог магазинов')}</a> — ${t('shopping categories','категории товаров')}.</li>
<li><a href="https://www.sarda-group.com/news/vzxsz85izkc3j3jnrcvyb3w7c4pwnq-8dgcp" target="_blank" rel="noopener noreferrer">SARDA Group</a> — ${t('fashion brands and aerial photograph','бренды одежды и фото с высоты')}.</li>
<li><a href="https://telegram.me/s/Tashkent_City_Mall?before=2586" target="_blank" rel="noopener noreferrer">${t('Official mall Telegram','Официальный Telegram молла')}</a> — ${t('Nike and adidas in the Back to School campaign','Nike и adidas в акции Back to School')}.</li>
<li><a href="https://tcmall.uz/uz/catalog/restaurants?sort=1&view=1" target="_blank" rel="noopener noreferrer">${t('Official dining directory','Официальный каталог заведений')}</a> — PAUL, SAFIA, TANUKI, BIG CHEFS, KFC, PIZZA HUT.</li>
<li><a href="https://cinematica.uz/" target="_blank" rel="noopener noreferrer">Cinematica</a> · <a href="https://t.me/s/Tashkent_City_Mall/552" target="_blank" rel="noopener noreferrer">${t('Mall announcement: IMAX','Публикация молла об IMAX')}</a> · <a href="https://tcmall.uz/ru/entertainments/skypark" target="_blank" rel="noopener noreferrer">Sky Park</a>.</li>
<li><a href="https://www.afisha.uz/uz/gorod/2024/11/26/barakalijuma" target="_blank" rel="noopener noreferrer">Afisha.uz</a> — ${t('atrium photograph','фотография атриума')}; <a href="https://www.afisha.uz/uz/shops/2024/07/23/citymall" target="_blank" rel="noopener noreferrer">Afisha.uz</a> — ${t('gallery interior photograph','фотография интерьера галерей')}.</li>
<li><a href="https://uz.kursiv.media/2024-02-29/kakie-magaziny-uzhe-nachali-rabotat-v-tashkent-city-mall/" target="_blank" rel="noopener noreferrer">Kursiv Media</a> — ${t('opening in 2024 and shopping photograph','открытие в 2024 году и фотография магазинов')}.</li>
<li><a href="https://tcmall.uz/en/rent" target="_blank" rel="noopener noreferrer">Tashkent City Mall</a> — ${t('exterior photograph','фотография фасада')}.</li>
</ol><p>${t('Brand names belong to their respective owners. Photographs are included with source attribution for this educational project. Product descriptions are examples of brand categories, not promises of stock or prices.','Названия брендов принадлежат их владельцам. Фотографии включены с указанием источников для учебного проекта. Описания товаров — примеры категорий брендов, а не обещание наличия или цен.')}</p></div></details></section>
</main><footer class="footer"><div class="wrap"><div class="footer-main"><a class="brand" href="#home"><span class="brand-mark">T</span><span class="brand-name">TASHKENT CITY<small>${t('A DIFFERENT KIND OF DAY','ДЕНЬ, КОТОРЫЙ ЗАПОМНИТСЯ')}</small></span></a><div class="credits"><strong>${t('Made by Rusinov David • 11A','Сделал Русинов Давид • 11А')}</strong><p>${t('Helped by Fedorishchev Artem • 11A','Помогал Федорищев Артём • 11А')}</p></div></div><div class="footer-bottom"><span>${t('2026 · ENGLISH SCHOOL PROJECT · TASHKENT, UZBEKISTAN','2026 · ШКОЛЬНЫЙ ПРОЕКТ ПО АНГЛИЙСКОМУ · ТАШКЕНТ, УЗБЕКИСТАН')}</span><a href="#home">${t('BACK TO TOP ↑','НАВЕРХ ↑')}</a></div></div></footer>
<dialog class="lightbox" aria-label="Photo gallery" data-label-en="Photo gallery" data-label-ru="Фотогалерея"><button class="lightbox-close" aria-label="Close gallery" data-label-en="Close gallery" data-label-ru="Закрыть галерею">×</button><img id="lightbox-image" alt=""><div class="lightbox-bottom"><span id="lightbox-caption"></span><div class="lightbox-nav"><button id="photo-prev" aria-label="Previous photograph" data-label-en="Previous photograph" data-label-ru="Предыдущее фото">←</button><button id="photo-next" aria-label="Next photograph" data-label-en="Next photograph" data-label-ru="Следующее фото">→</button></div></div></dialog>`;

let language='en';
function setLanguage(lang){
 language=lang;
 document.documentElement.lang=lang;
 document.querySelectorAll('[data-en]').forEach(el=>el.textContent=el.dataset[lang]);
 document.querySelectorAll('[data-alt-en]').forEach(el=>el.alt=lang==='en'?el.dataset.altEn:el.dataset.altRu);
 document.querySelectorAll('[data-label-en]').forEach(el=>el.setAttribute('aria-label',lang==='en'?el.dataset.labelEn:el.dataset.labelRu));
 document.querySelectorAll('[data-lang]').forEach(el=>{el.classList.toggle('active',el.dataset.lang===lang);el.setAttribute('aria-pressed',String(el.dataset.lang===lang));});
 document.title=lang==='en'?'Tashkent City Mall — A different kind of shopping day':'Tashkent City Mall — Новый взгляд на день покупок';
 document.querySelector('#navigation').setAttribute('aria-label',lang==='en'?'Main navigation':'Основная навигация');
 document.querySelector('.tabs').setAttribute('aria-label',lang==='en'?'Store categories':'Категории магазинов');
 if(dialog.open)updatePhoto();
}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{
 document.querySelectorAll('[data-filter]').forEach(tab=>{tab.classList.toggle('active',tab===b);tab.setAttribute('aria-pressed',String(tab===b));});
 document.querySelectorAll('[data-category]').forEach(card=>card.hidden=b.dataset.filter!=='all'&&card.dataset.category!==b.dataset.filter);
}));
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.navlinks');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='☰';}
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'×':'☰';});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
const dialog=document.querySelector('.lightbox');let photoIndex=0;
function updatePhoto(){const p=photos[photoIndex];document.querySelector('#lightbox-image').src='assets/'+p[0];document.querySelector('#lightbox-image').alt=p[language==='en'?3:4];document.querySelector('#lightbox-caption').textContent=`0${photoIndex+1} / 04 — ${p[language==='en'?1:2]}`;}
document.querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{photoIndex=Number(b.dataset.photo);updatePhoto();dialog.showModal();document.body.style.overflow='hidden';}));
function closePhoto(){dialog.close();}
dialog.addEventListener('close',()=>{document.body.style.overflow='';});
document.querySelector('.lightbox-close').addEventListener('click',closePhoto);
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closePhoto();}});
function changePhoto(delta){photoIndex=(photoIndex+delta+photos.length)%photos.length;updatePhoto();}
document.querySelector('#photo-prev').addEventListener('click',()=>changePhoto(-1));document.querySelector('#photo-next').addEventListener('click',()=>changePhoto(1));
dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();changePhoto(-1);}if(e.key==='ArrowRight'){e.preventDefault();changePhoto(1);}});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&'IntersectionObserver' in window){document.body.classList.add('motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}
